In [4]:
import numpy as np
import pandas as pd

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

In [5]:
df = pd.read_csv('Iris.csv')

In [6]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [127]:
df.Species[80]

'Iris-versicolor'

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [51]:
# Input datasets
inputs = df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
expected_output_1 = np.array([df.Species])

In [52]:
from sklearn.preprocessing import OneHotEncoder

In [123]:
expected_output_ = expected_output_1.reshape(-1, 1)

In [125]:
print(expected_output)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [124]:
encoder = OneHotEncoder(sparse=False)
expected_output = encoder.fit_transform(expected_output_)

In [10]:
x_train,x_test,y_train,y_test = train_test_split(inputs,expected_output,test_size=0.2,random_state=0)

NameError: name 'train_test_split' is not defined

In [11]:
from sklearn.model_selection import train_test_split

In [55]:
x_train,x_test,y_train,y_test = train_test_split(inputs,expected_output,test_size=0.2,random_state=0)

In [56]:
inputs.shape

(150, 4)

In [57]:
expected_output.shape

(150, 3)

In [91]:
inputLayerNeurons,hiddenLayerNeurons,outputLayerNeurons = 4,4,3

In [102]:
# Random weights and bias initialization
hidden_weights = np.random.uniform(size = (inputLayerNeurons,hiddenLayerNeurons))
hidden_bias = np.random.uniform(size = (120,hiddenLayerNeurons))

output_weights = np.random.uniform(size = (hiddenLayerNeurons,outputLayerNeurons))
output_bias = np.random.uniform(size = (120,outputLayerNeurons))

In [103]:
print('Initial hidden weights: ',end='')
print(*hidden_weights)
print('Initial hidden biases: ',end='')
print(*hidden_bias)
print('Initial output weights: ',end='')
print(*output_weights)
print('Initial output biases: ',end='')
print(*output_bias)

Initial hidden weights: [0.55107846 0.4264368  0.23726041 0.19621025] [0.52136344 0.9306889  0.28223236 0.60360683] [0.7082014  0.06030421 0.57658913 0.97209139] [0.39387893 0.06042487 0.3628223  0.77801856]
Initial hidden biases: [0.26980209 0.47363896 0.53517394 0.8477518 ] [0.63302456 0.96530291 0.89571171 0.22634494] [0.92136598 0.04945897 0.40817342 0.12626474] [0.31607949 0.64125829 0.08893709 0.25160392] [0.32565094 0.70613052 0.33251811 0.26748   ] [0.90889878 0.26085253 0.43620081 0.75734396] [0.13906337 0.29986191 0.77820775 0.59375326] [0.48549834 0.55337575 0.41594561 0.33336979] [0.14354979 0.02037719 0.06787274 0.79871053] [0.13216868 0.30424424 0.70897972 0.31388879] [0.02654871 0.27227743 0.09182705 0.06574737] [0.22715856 0.5818012  0.81844327 0.4485027 ] [0.23718553 0.51811028 0.86186873 0.62124936] [0.95313251 0.31576443 0.90526707 0.39826963] [0.17740529 0.17593432 0.20624886 0.73387218] [0.52571482 0.07654759 0.68888287 0.84893602] [0.43557442 0.41218219 0.02320679

In [112]:
output_weights.shape


(4, 3)

In [113]:
hidden_bias.shape

(120, 4)

In [98]:
epochs = 20000
lr = 0.1
m=4

In [118]:
# Training Algorithm
for _ in range(epochs):
    
    #Forward Propagation for finding predicted values
    hidden_layer_activation = np.dot(x_train,hidden_weights)
    hidden_layer_activation += hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)   #1st half completed
    
    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    output_layer_activation += output_bias
    predicted_output = sigmoid(output_layer_activation)      #2nd half completed
    
    #Backward Propagation for finding the weights
    error = y_train-predicted_output
    d_predicted_output = error*sigmoid_derivative(predicted_output)#Backward pass at output layer
    
    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer*sigmoid_derivative(hidden_layer_output)   #Backward pass at hidden layer
    
    #Updating Weights and Biases
    output_weights += hidden_layer_output.T.dot(d_predicted_output)*lr
    output_bias += np.sum(d_predicted_output,axis=0,keepdims=True)*lr
    hidden_weights += x_train.T.dot(d_hidden_layer)*lr
    hidden_bias += np.sum(d_hidden_layer,axis=1,keepdims=True)*lr

In [119]:
print('Final hidden weights: ',end='')
print(*hidden_weights)
print('Final hidden biases: ',end='')
print(*hidden_bias)
print('Final output weights: ',end='')
print(*output_weights)
print('Final output biases: ',end='')
print(*output_bias)

Final hidden weights: 0 1 2 3
Final hidden biases: [0.2824     0.48623688 0.54777186 0.86034972] [0.64537427 0.97765262 0.90806141 0.23869465] [0.88973386 0.01782685 0.37654131 0.09463263] [0.32025286 0.64543166 0.09311047 0.25577729] [0.36653185 0.74701143 0.37339902 0.30836091] [0.92123334 0.27318709 0.44853538 0.76967853] [0.11768902 0.27848756 0.75683341 0.57237892] [0.53847323 0.60635064 0.4689205  0.38634467] [0.13798087 0.01480828 0.06230383 0.79314161] [0.14341356 0.31548912 0.7202246  0.32513367] [0.06828263 0.31401135 0.13356097 0.10748129] [0.1705905  0.52523314 0.76187521 0.39193464] [0.23369109 0.51461585 0.85837429 0.61775492] [0.94020128 0.3028332  0.89233584 0.3853384 ] [0.13128884 0.12981787 0.16013241 0.68775572] [0.51157794 0.06241071 0.67474599 0.83479913] [0.47366066 0.45026843 0.06129304 0.70808394] [0.70072694 0.88797906 0.75991017 0.21564584] [0.93723574 0.44454522 1.01625674 0.68808805] [0.3948025  0.09135647 0.5293684  0.23835169] [0.4441044  0.45217927 0.4684

In [134]:
print('\nOutput from neutral network: ',end='')
print(*predicted_output)
for i in range(120):
    if predicted_output[i,0] >= 50:
        print('Flower ', i, 'is Iris-setosa')
    elif predicted_output[i,1] >= 50:
        print('Flower ', i, 'is Iris-versicolor')
    elif predicted_output[i,2] >= 50:
        print('Flower ', i, 'Iris-virginica')


Output from neutral network: [0.00266548 0.50497116 0.45296707] [0.00214219 0.56734381 0.46571308] [0.99711121 0.00400263 0.00160181] [0.00397769 0.58320027 0.46454677] [0.00411545 0.35577582 0.52316922] [0.00245453 0.49131772 0.49910505] [0.99597511 0.00397779 0.00280611] [0.00426139 0.44968512 0.4486838 ] [0.00320112 0.34971568 0.4375353 ] [0.00418344 0.4714138  0.5882058 ] [0.00273527 0.41395716 0.46722071] [0.9947358  0.00200322 0.00167406] [0.00352955 0.42429246 0.60082351] [0.99485794 0.00320528 0.00214791] [0.99577547 0.00257559 0.00134654] [0.00308803 0.42946355 0.43882895] [0.0031383  0.36312072 0.655958  ] [0.00184137 0.42371638 0.47414864] [0.00308667 0.38143876 0.5259573 ] [0.00423286 0.45768276 0.6155375 ] [0.0022715  0.38599797 0.52643648] [0.00192299 0.35113448 0.65724358] [0.00368483 0.4724378  0.44413024] [0.00242588 0.45811671 0.51719358] [0.0022168  0.35508361 0.45983986] [0.0024673  0.51432605 0.52467239] [0.00187037 0.52275905 0.46607601] [0.00382809 0.47085006 0.

In [135]:
predicted_output[0,0]

0.0026654835921915586

In [121]:
predicted_output.shape

(120, 3)

In [136]:
for i in range(120):
    if predicted_output[i,0] >= 0.50:
        print('Flower ', i, 'is Iris-setosa')
    elif predicted_output[i,1] >= 0.50:
        print('Flower ', i, 'is Iris-versicolor')
    elif predicted_output[i,2] >= 0.50:
        print('Flower ', i, 'Iris-virginica')

Flower  0 is Iris-versicolor
Flower  1 is Iris-versicolor
Flower  2 is Iris-setosa
Flower  3 is Iris-versicolor
Flower  4 Iris-virginica
Flower  6 is Iris-setosa
Flower  9 Iris-virginica
Flower  11 is Iris-setosa
Flower  12 Iris-virginica
Flower  13 is Iris-setosa
Flower  14 is Iris-setosa
Flower  16 Iris-virginica
Flower  18 Iris-virginica
Flower  19 Iris-virginica
Flower  20 Iris-virginica
Flower  21 Iris-virginica
Flower  23 Iris-virginica
Flower  25 is Iris-versicolor
Flower  26 is Iris-versicolor
Flower  27 Iris-virginica
Flower  28 Iris-virginica
Flower  29 is Iris-versicolor
Flower  30 is Iris-versicolor
Flower  31 is Iris-setosa
Flower  32 Iris-virginica
Flower  33 Iris-virginica
Flower  34 is Iris-versicolor
Flower  35 Iris-virginica
Flower  36 Iris-virginica
Flower  38 is Iris-setosa
Flower  39 is Iris-setosa
Flower  40 Iris-virginica
Flower  41 is Iris-versicolor
Flower  42 is Iris-setosa
Flower  43 is Iris-setosa
Flower  44 is Iris-versicolor
Flower  45 is Iris-setosa
Flowe